//! How deeply a JSON document nests, measured before it is parsed.
//!
//! The response a node sends is untrusted input for a tool like this one: it can be
//! truncated by a proxy, generated by a hostile endpoint, or simply enormous. Two
//! mechanisms already stop a stack overflow — `ureq` reads a bounded number of bytes and
//! `serde_json` refuses past 128 levels — but both fail in a way an operator cannot act on:
//! the second reports itself as a *parse error*, which reads as "this file is not JSON"
//! rather than "this trace nests 60,000 deep and necropsy will not recurse that far".
//!
//! A linear scan gives the number before any recursion starts, so the refusal can name it.
//! It is deliberately not a parser: it tracks only what changes the answer — string
//! delimiters and the escapes inside them — and treats everything else as structure.

use crate::error::{Error, Result};
use serde::Deserialize;
use serde_json::Value;

/// Deepest nesting level reached, counted in `{`/`[` opens that are outside string
/// literals. Unterminated input returns the depth reached so far; the parser that follows
/// is the thing that says whether the document is valid.
pub fn max_nesting(bytes: &[u8]) -> usize {
    let mut depth = 0usize;
    let mut max = 0usize;
    let mut in_string = false;
    let mut escaped = false;

    for &b in bytes {
        if in_string {
            if escaped {
                escaped = false;
            } else if b == b'\\' {
                escaped = true;
            } else if b == b'"' {
                in_string = false;
            }
            continue;
        }
        match b {
            b'"' => in_string = true,
            b'{' | b'[' => {
                depth += 1;
                max = max.max(depth);
            }
            b'}' | b']' => depth = depth.saturating_sub(1),
            _ => {}
        }
    }
    max
}

/// Parse a document that nobody has vouched for, under an explicit depth bound.
///
/// Two halves, in this order, and the order is the point:
///
///   1. [`max_nesting`] measures the structure without recursing into it.
///   2. only then is `serde_json`'s own 128-level limit switched off, so a deeper document
///      is refused by *our* number rather than by a parser that reports it as invalid JSON.
///
/// Reversing them is how a 60,000-level file becomes a stack overflow: with the limit off
/// and nothing checking first, the recursion is the process's own.
pub fn bounded_value(bytes: &[u8], max_depth: usize) -> Result<Value> {
    let depth = max_nesting(bytes);
    if depth > max_depth {
        return Err(Error::TraceTooDeep {
            depth,
            limit: max_depth,
        });
    }
    let mut de = serde_json::Deserializer::from_slice(bytes);
    de.disable_recursion_limit();
    let value =
        Value::deserialize(&mut de).map_err(|e| Error::Collect(format!("not valid JSON: {e}")))?;
    de.end()
        .map_err(|e| Error::Collect(format!("trailing data after the JSON document: {e}")))?;
    Ok(value)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn a_document_past_the_bound_is_refused_by_our_number_not_the_parsers() {
        // The message has to be actionable: which limit, what the document did, which flag
        // moves it. A `serde_json` recursion error would say none of those.
        let deep = format!("{}1{}", "[".repeat(200), "]".repeat(200));
        let e = bounded_value(deep.as_bytes(), 128).unwrap_err();
        assert!(matches!(e, Error::TraceTooDeep { depth: 200, .. }), "{e}");
        assert!(e.to_string().contains("--max-trace-depth"), "{e}");
        // Same document, one level of room: parses.
        assert!(bounded_value(deep.as_bytes(), 200).is_ok());
    }

    #[test]
    fn past_serdes_own_limit_still_parses_when_the_bound_allows_it() {
        // This is the capability the feature exists for. 130 levels is a legal document that
        // `serde_json::from_slice` alone refuses.
        let deep = format!("{}1{}", "[".repeat(130), "]".repeat(130));
        assert!(serde_json::from_str::<serde_json::Value>(&deep).is_err());
        assert!(bounded_value(deep.as_bytes(), 2048).is_ok());
    }

    #[test]
    fn malformed_and_trailing_input_are_errors_not_panics() {
        assert!(bounded_value(b"{", 128).is_err());
        assert!(bounded_value(b"{} {}", 128).is_err());
        assert!(bounded_value(b"<html>502 Bad Gateway</html>", 128).is_err());
        let ok = bounded_value(json!({"result": [1, 2]}).to_string().as_bytes(), 128);
        assert!(ok.is_ok(), "{ok:?}");
    }

    #[test]
    fn brackets_inside_strings_are_not_nesting() {
        // A trace frame's `input` is a hex string, and an address or error blob can hold
        // anything. Counting a brace in a string would refuse a valid document.
        assert_eq!(max_nesting(br#"{"input":"0x{{{{[[","to":"a}b"}"#), 1);
    }

    #[test]
    fn an_escaped_quote_does_not_end_the_string() {
        // `"a\"{("` is one string; the brace inside it must not count.
        assert_eq!(max_nesting(br#"{"s":"a\"{(","t":1}"#), 1);
    }

    #[test]
    fn nesting_counts_objects_and_arrays_together() {
        // 1: the root object, 2: "calls", 3: its inner array, 4: the frame object,
        // 5: the array that is that frame's "x". Hand-counted once, then confirmed by the
        // scanner agreeing — a wrong expectation here would silently redefine the guard.
        assert_eq!(max_nesting(br#"{"calls":[[{"x":{}},[]]]}"#), 5);
    }

    #[test]
    fn a_flat_array_of_many_frames_is_shallow() {
        // The shape a real wide trace has: 3,000 siblings, depth 2. Whatever the byte
        // count, this is not the input the depth guard exists to refuse.
        let json = format!("{{\"calls\":[{}]}}", "1,".repeat(3000));
        assert_eq!(max_nesting(json.as_bytes()), 2);
    }

    #[test]
    fn truncated_input_reports_the_depth_reached() {
        assert_eq!(max_nesting(b"[[[[[1,2"), 5);
    }

    #[test]
    fn an_empty_or_non_json_document_reports_zero_or_one() {
        assert_eq!(max_nesting(b""), 0);
        assert_eq!(max_nesting(b"null"), 0);
        assert_eq!(max_nesting(b"garbage"), 0);
    }

    #[test]
    fn the_captured_fixture_is_shallow_enough_to_read() {
        let raw = std::fs::read(format!(
            "{}/tests/fixtures/usdc-transfer-18214590.calltracer.json",
            env!("CARGO_MANIFEST_DIR")
        ))
        .expect("the committed fixture");
        assert!(
            max_nesting(&raw) <= 128,
            "the fixture would be refused by the guard it is meant to exercise"
        );
    }
}
